- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis is installed.
  package:
    name: "{{ redis_package }}"
    state: present
    enablerepo: "{{ redis_enablerepo }}"

- include_tasks: init-systemd.yml
  when: ansible_service_mgr == 'systemd'

- include_tasks: init-sysv.yml
  # upstart (used on amilinux-1) has backwards compat with sysvinit scripts
  when: ansible_service_mgr == 'sysvinit' or ansible_service_mgr == 'upstart'

- name: Make sure directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755
  with_items:
    - "{{ redis_dbdir }}"
    - "{{ redis_piddir }}"

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

# This avoids OOM errors when redis saves to disk!
#
# Please see "Background saving fails with a fork() error under Linux even if I have a lot of free RAM!"
# here https://redis.io/topics/faq
#
# This needs to be enabled only when we have snapshotting.
- name: Enable memory overcommit kernel param
  sysctl:
    name: vm.overcommit_memory
    value: 1
    reload: yes
    state: present
  when: redis_persistence_enable

- name: Increase somaxconn kernel param
  sysctl:
    name: net.core.somaxconn
    value: "{{ redis_somaxconn }}"
    reload: yes
    state: present

- name: Make sure rc.local is executable
  file:
    path: /etc/rc.d/rc.local
    state: file
    mode: 0750

- name: Disable Transparent Huge Pages on boot to help latency
  lineinfile:
    path: /etc/rc.d/rc.local
    state: present
    line: "{{ item }}"
  with_items:
    - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    - "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  register: _redis_enabled_thd
  notify: restart redis

- name: Disable THP now if just added
  shell: "{{ item }}"
  with_items:
    - "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    - "echo never > /sys/kernel/mm/transparent_hugepage/defrag"
  when: _redis_enabled_thd.changed

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
