---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis is installed.
  package:
    name: "{{ redis_package }}"
    state: present
    enablerepo: "{{ redis_enablerepo }}"

- include_tasks: init-systemd.yml
  when: ansible_service_mgr == 'systemd'

- include_tasks: init-systemd.yml
  when: ansible_service_mgr == 'sysvinit'

- name: Make sure dbdir exists.
  file:
    path: "{{ redis_dbdir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
